export type MerchandiseItem = {
  id: string;
  name: string;
  image: string;
  price: string;
  link: string;
};

export type Athlete = {
  slug: string;
  name: string;
  position: string;
  school: string;
  conference: string;
  classYear: string;
  number?: string;
  bio?: string;
  image: string;
  colors: { from: string; to: string };
  stats: {
    passingYards: number;
    rushingYards: number;
    receivingYards: number;
    touchdowns: number;
    interceptions: number;
    tackles: number;
    sacks: number;
  };
  merchandise?: MerchandiseItem[];
  hasMerchandise: boolean;
};

export const athletes: Athlete[] = [
  {
    slug: "madden-faraimo",
    name: "Madden Faraimo",
    position: "Linebacker",
    school: "Notre Dame",
    conference: "Independent",
    classYear: "Sophomore",
    number: "45",
    bio: "Physical linebacker with excellent instincts and tackling ability. Leader on the defensive side of the ball.",
    image: "/players/madden_faraimo.webp",
    colors: { from: "from-blue-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "rico-flores-jr",
    name: "Rico Flores Jr.",
    position: "Wide Receiver",
    school: "UCLA",
    conference: "Big Ten",
    classYear: "Sophomore",
    number: "4",
    bio: "Polished route runner with reliable hands and YAC ability. Creates separation with pacing and leverage.",
    image: "/players/rico_flores.webp",
    colors: { from: "from-blue-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "jacob-de-jesus",
    name: "Jacob De Jesus",
    position: "Wide Receiver",
    school: "Cal",
    conference: "ACC",
    classYear: "Senior",
    number: "1",
    bio: "Electric receiver with elite short-area quickness and field vision. Game-changer on offense and special teams.",
    image: "/players/jacob_de_jesus.webp",
    colors: { from: "from-blue-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "jack-pedersen",
    name: "Jack Pedersen",
    position: "Tight End",
    school: "UCLA",
    conference: "Big Ten",
    classYear: "Junior",
    number: "87",
    bio: "Versatile tight end with strong blocking skills and reliable hands. Creates mismatches in the passing game.",
    image: "/players/jack_pedersen.jpg",
    colors: { from: "from-blue-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "christian-pierce",
    name: "Christian Pierce",
    position: "Safety",
    school: "USC",
    conference: "Big Ten",
    classYear: "Junior",
    number: "27",
    bio: "Physical, disciplined safety with range and playmaking instincts. Communicator on the back end.",
    image: "/players/christian_pierce.webp",
    colors: { from: "from-red-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "alzillion-hamilton",
    name: "Al'Zillion Hamilton",
    position: "Cornerback",
    school: "Fresno State",
    conference: "Mountain West",
    classYear: "Senior",
    number: "23",
    bio: "Lockdown corner with elite speed and ball skills. Shuts down opposing receivers with physical play.",
    image: "/players/al'zillion_hamiliton.webp",
    colors: { from: "from-blue-600", to: "to-red-600" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "jadyn-hudson",
    name: "Jadyn Hudson",
    position: "Safety",
    school: "UCLA",
    conference: "Big Ten",
    classYear: "Sophomore",
    number: "3",
    bio: "Rangy safety with excellent coverage skills and ball-hawking ability. Leader of the secondary.",
    image: "/players/jadyn_hudson.webp",
    colors: { from: "from-blue-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "michael-tollefson",
    name: "Michael 'Butter' Tollefson",
    position: "Quarterback",
    school: "Arizona State University",
    conference: "Big 12",
    classYear: "Junior",
    number: "12",
    bio: "Dual-threat quarterback with strong arm and mobility. Natural leader who makes plays under pressure.",
    image: "/players/michael_tollefson.webp",
    colors: { from: "from-maroon-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "zachary-card",
    name: "Zachary Card",
    position: "Wide Receiver",
    school: "Oregon State University",
    conference: "Pac-12",
    classYear: "Sophomore",
    number: "8",
    bio: "Explosive receiver with breakaway speed and reliable hands. Creates big plays down the field.",
    image: "/players/zachary_card.webp",
    colors: { from: "from-orange-600", to: "to-black" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "grant-buckey",
    name: "Grant Buckey",
    position: "Defensive Lineman",
    school: "UCLA",
    conference: "Big Ten",
    classYear: "Junior",
    number: "99",
    bio: "Physical defensive lineman with strong hands and motor. Disrupts plays in the backfield consistently.",
    image: "/players/grant_buckey.webp",
    colors: { from: "from-blue-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "michael-dansby",
    name: "Michael Dansby",
    position: "Cornerback",
    school: "University of Arizona",
    conference: "Big 12",
    classYear: "Senior",
    number: "21",
    bio: "Shutdown corner with excellent technique and ball skills. Matches up against top receivers.",
    image: "/players/michael_dansby.webp",
    colors: { from: "from-red-600", to: "to-blue-600" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "marquis-gallegos",
    name: "Marquis Gallegos",
    position: "Safety",
    school: "USC",
    conference: "Big Ten",
    classYear: "Sophomore",
    number: "15",
    bio: "Hard-hitting safety with excellent range and tackling ability. Leader of the defensive backfield.",
    image: "/players/marquis_gallegos.jpg",
    colors: { from: "from-red-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "sefo-akuila",
    name: "Sefo Akuila",
    position: "Linebacker",
    school: "BYU",
    conference: "Big 12",
    classYear: "Junior",
    number: "44",
    bio: "Physical linebacker with excellent instincts and tackling ability. Leader on the defensive side.",
    image: "/players/sefo_akuila.webp",
    colors: { from: "from-blue-600", to: "to-white" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "skyler-thomas",
    name: "Skyler Thomas",
    position: "Safety",
    school: "Oregon State University",
    conference: "Pac-12",
    classYear: "Senior",
    number: "7",
    bio: "Versatile safety with excellent coverage skills and ball-hawking ability. Leader of the secondary.",
    image: "/players/skyler_thomas.webp",
    colors: { from: "from-orange-600", to: "to-black" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "bryce-cain",
    name: "Bryce Cain",
    position: "Wide Receiver",
    school: "Auburn",
    conference: "SEC",
    classYear: "Sophomore",
    number: "11",
    bio: "Explosive receiver with breakaway speed and reliable hands. Creates big plays down the field.",
    image: "/players/bryce_cain.webp",
    colors: { from: "from-orange-600", to: "to-blue-600" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "derrick-blanche-jr",
    name: "Derrick Blanche Jr.",
    position: "Running Back",
    school: "Portland State University",
    conference: "Big Sky",
    classYear: "Junior",
    number: "22",
    bio: "Powerful running back with excellent vision and breakaway speed. Workhorse of the offense.",
    image: "/players/derrick_blanche.webp",
    colors: { from: "from-green-600", to: "to-white" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "cynai-thomas",
    name: "Cynai Thomas",
    position: "Wide Receiver",
    school: "Archbishop Riordan High School",
    conference: "High School",
    classYear: "Senior",
    number: "5",
    bio: "Elite high school receiver with exceptional route running and hands. Future star at the next level.",
    image: "/players/cynai_thomas.webp",
    colors: { from: "from-purple-600", to: "to-gold-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "naki-tuakoi",
    name: "Naki Tuakoi",
    position: "Linebacker",
    school: "BYU",
    conference: "Big 12",
    classYear: "Sophomore",
    number: "33",
    bio: "Physical linebacker with excellent instincts and tackling ability. Leader on the defensive side.",
    image: "/players/naki_tuakoi.webp",
    colors: { from: "from-blue-600", to: "to-white" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "herschel-turner",
    name: "Herschel Turner",
    position: "Running Back",
    school: "Nevada",
    conference: "Mountain West",
    classYear: "Senior",
    number: "28",
    bio: "Powerful running back with excellent vision and breakaway speed. Workhorse of the offense.",
    image: "/players/herschel_turner.webp",
    colors: { from: "from-blue-600", to: "to-silver-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "kedren-young",
    name: "Kedren Young",
    position: "Running Back",
    school: "Notre Dame",
    conference: "Independent",
    classYear: "Freshman",
    number: "25",
    bio: "Elite freshman running back with exceptional talent and potential. Future star for the Fighting Irish.",
    image: "/players/kedren_young.webp",
    colors: { from: "from-blue-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "ansu-sanoe",
    name: "Ansu Sanoe",
    position: "Running Back",
    school: "Lakeridge High School",
    conference: "High School",
    classYear: "Senior",
    number: "24",
    bio: "Elite high school running back with exceptional speed and power. Future star at the next level.",
    image: "/players/ansu_sanoe.webp",
    colors: { from: "from-blue-600", to: "to-white" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "tyson-ruffins",
    name: "Tyson Ruffins",
    position: "Offensive Guard",
    school: "Cal",
    conference: "ACC",
    classYear: "Junior",
    number: "77",
    bio: "Physical offensive guard with excellent technique and strength. Anchors the offensive line.",
    image: "/players/tyson_ruffins.webp",
    colors: { from: "from-blue-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "maliki-crawford",
    name: "Maliki Crawford",
    position: "Cornerback",
    school: "USC",
    conference: "Big Ten",
    classYear: "Sophomore",
    number: "19",
    bio: "Shutdown corner with excellent technique and ball skills. Matches up against top receivers.",
    image: "/players/maliki_crawford.webp",
    colors: { from: "from-red-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "jadyn-marshall",
    name: "Jadyn Marshall",
    position: "Cornerback",
    school: "UCLA",
    conference: "Big Ten",
    classYear: "Sophomore",
    number: "2",
    bio: "Elite cornerback with exceptional speed and coverage skills. Shuts down opposing receivers.",
    image: "/players/jadyn_marshall.webp",
    colors: { from: "from-blue-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "kenny-moore-iii",
    name: "Kenny Moore III",
    position: "Wide Receiver",
    school: "UCLA",
    conference: "High School",
    classYear: "Senior",
    number: "9",
    bio: "Elite high school receiver with exceptional route running and hands. Future star for UCLA.",
    image: "/players/kenny_moore.webp",
    colors: { from: "from-blue-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "blake-wong",
    name: "Blake Wong",
    position: "Wide Receiver",
    school: "Norco High School",
    conference: "High School",
    classYear: "Senior",
    number: "6",
    bio: "Elite high school receiver with exceptional speed and hands. Future star at the next level.",
    image: "/players/blake_wong.webp",
    colors: { from: "from-red-600", to: "to-white" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "raiqwon-oneal",
    name: "Raiqwon O'Neal",
    position: "Offensive Tackle",
    school: "Tampa Bay Buccaneers",
    conference: "NFL",
    classYear: "Pro",
    number: "70",
    bio: "NFL offensive tackle with excellent technique and strength. Protects the quarterback at the highest level.",
    image: "/players/raiqwon_oneal.webp",
    colors: { from: "from-red-600", to: "to-white" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "myles-purchase",
    name: "Myles Purchase",
    position: "Cornerback",
    school: "Los Angeles Chargers",
    conference: "NFL",
    classYear: "Pro",
    number: "29",
    bio: "NFL cornerback with exceptional speed and coverage skills. Shuts down opposing receivers at the highest level.",
    image: "/players/myles_purchase.webp",
    colors: { from: "from-blue-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "justin-lockhart",
    name: "Justin Lockhart",
    position: "Wide Receiver",
    school: "Kansas City Chiefs",
    conference: "NFL",
    classYear: "Pro",
    number: "18",
    bio: "NFL wide receiver with exceptional route running and hands. Creates big plays at the highest level.",
    image: "/players/justin_lockhart.webp",
    colors: { from: "from-red-600", to: "to-yellow-500" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
  {
    slug: "tuasivi-nomura",
    name: "Tuasivi Nomura",
    position: "Linebacker",
    school: "Carolina Panthers",
    conference: "NFL",
    classYear: "Pro",
    number: "55",
    bio: "NFL linebacker with excellent instincts and tackling ability. Leader on the defensive side at the highest level.",
    image: "/players/tuasivi_nomura.webp",
    colors: { from: "from-blue-600", to: "to-black" },
    stats: {
      passingYards: 0,
      rushingYards: 0,
      receivingYards: 0,
      touchdowns: 0,
      interceptions: 0,
      tackles: 0,
      sacks: 0,
    },
    hasMerchandise: false,
    merchandise: [],
  },
];


